@HostAddress = http://localhost:5216

GET {{HostAddress}}/

###

GET {{HostAddress}}/tools/time

###

GET {{HostAddress}}/tools/date

###

GET {{HostAddress}}/tools/info

###

GET {{HostAddress}}/tools/time?trace=true

###

GET {{HostAddress}}/anything?format=plain

###

GET {{HostAddress}}/secure/report

###

GET {{HostAddress}}/secure/report?token=study2026

###

GET {{HostAddress}}/env

###

GET {{HostAddress}}/di/services

###

GET {{HostAddress}}/unknown
